UI changed
MetaVASP/Zipify pull request #20
Opened 2022-03-01 18:32 UTC by ishika1501

#1  issue resolved , the UI has been updated , sir please mention if any future changes are required.

2022-03-03 06:01 UTC, pulkit-30 requested changes

2022-03-03 06:01 UTC, pulkit-30 commented on public/css/style.css
> +  --primary-color: #DEB841;
Ui doesn't respond!!!

2022-03-03 06:14 UTC, ishika1501 commented
@pulkit-30 i have understood the things you mentioned , i will improve it and push it again , thankyou for your corporation. i am getting it done as soon as possible .Thankyou sir

2022-03-03 06:21 UTC, Ayush7614 requested changes
@ishika1501 Doing Changes Correctly

2022-03-03 13:30 UTC, pulkit-30 requested changes

2022-03-03 13:30 UTC, pulkit-30 commented on public/css/style.css
> +<<<<<<< HEAD
By mistake, you have pushed the conflicting code

2022-03-05 15:16 UTC, pulkit-30 commented
Any Update?

2022-03-06 01:55 UTC, ishika1501 commented on public/css/style.css
> +<<<<<<< HEAD
i am getting this done sir .sorry for that.

2022-03-07 13:26 UTC, ishika1501 commented
@pulkit-30  sir  hopefully i have resolved the issue , please accept it .

2022-03-07 14:03 UTC, pulkit-30 requested changes

2022-03-07 14:03 UTC, pulkit-30 commented on public/css/style.css
> +}
Use Css variables for background colors
ref - https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties

2022-04-10 05:10 UTC, merged

2022-04-10 05:10 UTC, pulkit-30 commented
Great Work @ishika1501 🎉 
Thanks