Updated logo
MetaVASP/Zipify pull request #38
Opened 2022-03-20 10:05 UTC by priyanshi1282

## 🛠️ Fixes Issue #29 

## 👨‍💻 Changes proposed
Updated the Logo of Zipify.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
![screenshot](https://user-images.githubusercontent.com/88632352/159157348-ebf65e94-67c4-4fc8-abb2-935f1c27565d.png)

###  Please consider this contribution under GSSoC'22.

2022-03-20 11:03 UTC, pulkit-30 requested changes

2022-03-20 11:03 UTC, pulkit-30 commented on views/components/header.ejs
> +<!-- <img src="./logo.png" alt="logo"> -->
Delete this

2022-03-20 11:03 UTC, pulkit-30 commented on views/index.ejs
> +  <!-- <img src="./logo-black.png" alt="logo-black" class="logo-black" /> -->
Delete this !

2022-03-20 13:27 UTC, priyanshi1282 commented
Hey @pulkit-30 I did required changes.

2022-03-20 13:39 UTC, pulkit-30 approved these changes
Great Thanks 🎉

2022-03-20 13:40 UTC, merged

2022-03-20 14:22 UTC, priyanshi1282 commented
> Great Thanks 🎉

It was nice working with you 😀

2022-04-16 16:50 UTC, priyanshi1282 commented
Hey @pulkit-30, @Ayush7614  I think you have to add level0/1/2/3 label also so that I can get points for this PR.